-- 03_postgresql_creacion.sql
-- Base de gestión de clientes, sucursales, metas y satisfacción.
-- Docker Compose ya crea la base farmacia_db.

DROP SCHEMA IF EXISTS gestion CASCADE;
CREATE SCHEMA gestion;
SET search_path TO gestion, public;

CREATE TABLE zona (
    codigo_zona VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    responsable VARCHAR(100)
);

CREATE TABLE sucursal (
    codigo_sucursal VARCHAR(10) PRIMARY KEY,
    nombre_oficial VARCHAR(100) NOT NULL,
    codigo_zona VARCHAR(10) REFERENCES zona(codigo_zona),
    ciudad VARCHAR(80),
    direccion VARCHAR(160),
    latitud NUMERIC(9,6),
    longitud NUMERIC(9,6),
    fecha_apertura DATE,
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE segmento_cliente (
    codigo_segmento VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    descripcion VARCHAR(200)
);

CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(25),
    nombres VARCHAR(120) NOT NULL,
    ciudad VARCHAR(80),
    fecha_nacimiento DATE,
    sexo CHAR(1),
    codigo_segmento VARCHAR(10) REFERENCES segmento_cliente(codigo_segmento),
    fecha_registro DATE,
    correo VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE
    -- documento no es UNIQUE a propósito: existen duplicados que el ETL debe detectar.
);

CREATE TABLE meta_mensual (
    codigo_sucursal VARCHAR(10) REFERENCES sucursal(codigo_sucursal),
    periodo DATE NOT NULL,
    meta_ventas NUMERIC(12,2) NOT NULL,
    meta_clientes INTEGER,
    PRIMARY KEY (codigo_sucursal, periodo)
);

CREATE TABLE encuesta_satisfaccion (
    id_encuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    codigo_sucursal VARCHAR(10) REFERENCES sucursal(codigo_sucursal),
    documento_cliente VARCHAR(25),
    puntuacion INTEGER,
    tiempo_espera_minutos INTEGER,
    comentario VARCHAR(300)
);

CREATE INDEX idx_cliente_documento ON cliente(documento);
CREATE INDEX idx_encuesta_fecha ON encuesta_satisfaccion(fecha);
CREATE INDEX idx_meta_periodo ON meta_mensual(periodo);
