services:
  ventas:
    image: mysql:8.4
    container_name: ventas
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: farmacia_db
      MYSQL_USER: victor
      MYSQL_PASSWORD: victor123
    ports:
      - "3307:3306"
    volumes:
      - ../../data/ventas_data:/var/lib/mysql
      - ./ventas-init:/docker-entrypoint-initdb.d:ro

  gestion:
    image: postgres:16
    container_name: gestion
    environment:
      POSTGRES_DB: farmacia_db
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: victor123
    ports:
      - "5432:5432"
    volumes:
      - ../../data/gestion_data:/var/lib/postgresql/data
      - ./gestion-init:/docker-entrypoint-initdb.d:ro

  staging:
    image: postgres:16
    container_name: staging
    environment:
        POSTGRES_DB: datawarehouse
        POSTGRES_USER: victor
        POSTGRES_PASSWORD: victor123
    ports:
      - "5450:5432"
    volumes:
      - ../../data/datawarehouse_data:/var/lib/postgresql/data
      - ./datawarehouse-init:/docker-entrypoint-initdb.d:ro

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
  
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports: 
      - "8090:8080"
    depends_on:
      - gestion
      - ventas
      - staging

  rstudio:
    build:
      context: ./rstudio
    container_name: bi_rstudio
    environment:
      PASSWORD: rstudio123
      DW_HOST: staging
      DW_PORT: 5432
      DW_DATABASE: datawarehouse
      DW_USER: victor
      DW_PASSWORD: victor123
    ports:
      - "8787:8787"
    volumes:
      - ./rstudio/proyecto:/home/rstudio/proyecto
    depends_on:
      - staging
    restart: unless-stopped